// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Testcase1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testcase1() {
    driver.get("https://demoqa.com/automation-practice-form");
    driver.manage().window().setSize(new Dimension(1209, 643));
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector("#cbb path")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector(".show #item-0")).click();
    driver.findElement(By.cssSelector(".show #item-0")).click();
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("Udara");
    driver.findElement(By.id("lastName")).sendKeys("Vimukthi");
    driver.findElement(By.id("userNumber")).sendKeys("0766503566");
    driver.findElement(By.id("currentAddress")).sendKeys("No: 439/3, Siyambalape North, Siyambalape");
    driver.findElement(By.id("userEmail")).click();
    {
      WebElement element = driver.findElement(By.id("userEmail"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".custom-radio:nth-child(1) > .custom-control-label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".custom-radio:nth-child(1) > .custom-control-label"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".col-md-4:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".css-1pahdxg-control > .css-1hwfws3")).click();
    driver.findElement(By.id("react-select-3-option-3")).click();
    driver.findElement(By.cssSelector(".custom-checkbox:nth-child(1) > .custom-control-label")).click();
    driver.findElement(By.cssSelector(".subjects-auto-complete__value-container")).click();
    driver.findElement(By.id("subjectsInput")).sendKeys("OOP");
    driver.findElement(By.id("userEmail")).click();
    driver.findElement(By.id("userEmail")).sendKeys("uvlakshan@gmail.com");
    driver.findElement(By.cssSelector(".subjects-auto-complete__value-container")).click();
    driver.findElement(By.id("subjectsInput")).sendKeys("OOP");
    driver.findElement(By.cssSelector(".mt-2:nth-child(8) > .col-md-3")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mt-2:nth-child(8) > .col-md-3"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".css-1pahdxg-control > .css-1hwfws3")).click();
    driver.findElement(By.id("react-select-4-option-1")).click();
    driver.findElement(By.id("submit")).click();
  }
}
